### ISSUE TITLE
Is there a source file for these diagrams?

### ISSUE THREAD

**Issue by blaisep** [bravok/hachyderm-architecture#1]
@bravok I suppose this is more of a question.
If I wanted to extend, or update the diagrams, where would I find the source file?

**Comment by bravok** [comment]
Hi, yes.

Source file is at https://github.com/bravok/hachyderm-architecture/blob/main/hachyderm.io.archimate. Feel free to fork and load it into Archi (https://www.archimatetool.com/) to edit.

**Comment by blaisep** [comment]
Oh! thank you , I see it.
